n = input('Digite algo: ')
print('O tipo primitivo desse valor é : ',type(n))
print('Só tem espaço? ',n.isspace())
print('É um número? ',n.isnumeric())
print('É alfabetico? ',n.isalpha())
print('É alfanúmerico? ',n.isalnum())
print('Ésta em maiúsculas? ',n.isupper())
print('Ésta em maiúsculas? ',n.islower())
print('Ésta capitalizada? ',n.istitle())
