nome = str(input('DIGITE NOME COMPLETO: ')).strip()
print('Analizando seu nome ...')
print(nome)
print('Seu nome em Maiúsculas é: {}'.format(nome.upper()))
print('Seu nome em Minúsculas é: {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('Seu primeiro nome tem {} letras '.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome tem {} letras'.format(len(separa[0])))